### PR TITLE
Fix indentation and remove trailing whitespaces from Git helpers

### PR DESCRIPTION
**Pull request by mokagio**
What I actually wanted to do was the change in the next #176, but before doing that I had to come through this. My text editor pointed these out.

### CODE REVIEW

**Comment by loremattei** [comment]
I never know how to review these PRs because the way the diff are presented makes it difficult to figure out if something got deleted by mistake or any other change happened 🤔
What I know is that without a way to check these rules locally, we'll probably have this problem back again in the future. What do you think about adding a `.editor-config` file to this PR?

**Comment by AliSoftware** [comment]
> I never know how to review these PRs because the way the diff are presented makes it difficult to figure out if something got deleted by mistake or any other change happened 🤔

@loremattei did you know about this option in GitHub?

GitHub-Whitespace-Option

**Review by AliSoftware — APPROVED** [review]
GitHub shows that it's indeed only whitespace changes, so LGTM 👍 

But I agree with Lore that this PR could be a good occasion to finally add that `.editorconfig` file here indeed!!

**Comment by loremattei** [comment]
> @loremattei did you know about this option in GitHub?

Ah! Right @AliSoftware! I think I actually knew about this, but I keep forgetting that it's there! Thanks for the reminder! It's actually super useful 🙇

**Pull request merged**
