### PR TITLE
Fix PR validity check in `create_release_backmerge_pr`

### PR DESCRIPTION
**Pull request by AliSoftware**
## Why?

Our logic for testing if the backmerge PR would be valid or rejected by GitHub was incorrect.
 - Indeed, so far we checked if the `head` and `base` of the PR about to be created returned `true` for `point_to_same_commit?`. Which would never be true, as even if there were no new commit on the `head` branch since the last backmerge PR into the `base` branch, those would still be two different commits (due to the merge commit in `base` being created from the last backmerge PR).
 - Also worth noting that even if the diff between `head` and `base` were empty, it would technically still be valid to create a PR between the two, because one could have added a commit and its revert on the `head` branch since the last backmerge of `head` into `base`, resulting in an empty `diff` in the PR, but still a valid PR as some commits from `head` would not be on `base` branch yet and would still be ok to merge to reconcile the git graph / history.

[GitHub uses the three-dots diff to create Pull Requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons), meaning it uses [`git diff base...head` (aka `git diff $(git merge-base base head) head`)](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt-emgitdiffemltoptionsgtltcommitgtltcommitgt--ltpathgt82308203-1) to only include the diff since the **common ancestor** (merge-base) of the base branch and the head branch.

We thus need to use a similar logic in our action, to detect if GitHub would consider that there was nothing to merge and would reject the PR creation before even attempting to do the API call to create the PR.

## How?

This PR fixes the logic to check if PR would be invalid (nothing to merge), by first finding the `merge-base` between the two branches and checking if the merge base is the same as the head commit we are trying to merge.
If so, that means that there were no new commits on the head branch since it was last cut or last merged into the base branch. In other words, all the commits in the head branch are already in the base branch too (are already part of the common ancestor tree). And in such case there is nothing new to merge, so we should skip the PR creation

This PR also fixes the call to `ensure_git_branch` after having called the callback optionally provided by the user, as it had a typo in the regex used.

## Checklist before requesting a review

- [x] Run `bundle exec rubocop` to test for code style violations and recommendations
- [x] Add Unit Tests (aka `specs/*_spec.rb`) if applicable
- [x] Run `bundle exec rspec` to run the whole test suite and ensure all your tests pass
- [x] Make sure you added an entry in [the `CHANGELOG.md` file](https://github.com/wordpress-mobile/release-toolkit/blob/trunk/CHANGELOG.md#trunk) to describe your changes under the appropriate existing `###` subsection of the existing `## Trunk` section.
- [x] If applicable, add an entry in [the `MIGRATION.md` file](https://github.com/wordpress-mobile/release-toolkit/blob/trunk/MIGRATION.md) to describe how the changes will affect the migration from the previous major version and what the clients will need to change and consider.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please add an entry in the CHANGELOG.md file to describe the changes made by this PR</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">This PR is still a Draft: some checks will be skipped.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by iangmaia** [comment]
I've tried to run a simple test:
- In DOAndroid, I've created a branch `iangmaia/test-fix-backmerge-pr-validity-check` pointing release-toolkit to this branch
- I've added a test lane https://github.com/bloom/DayOne-Android/blob/fc9356c15cba2d03b25112c6397b1c27949b4213/fastlane/Fastfile#L748
- I've then branched off this branch on `iangmaia/test-fix-backmerge-pr-validity-check-target`

The result:
```console
[19:16:35]: Creating new pull request from 'merge/iangmaia-test-fix-backmerge-pr-validity-check-into-iangmaia-test-fix-backmerge-pr-validity-check-target' to branch 'iangmaia/test-fix-backmerge-pr-validity-check-target' of 'bloom/DayOne-Android'
[19:16:35]: GitHub responded with 422: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"No commits between iangmaia/test-fix-backmerge-pr-validity-check-target and merge/iangmaia-test-fix-backmerge-pr-validity-check-into-iangmaia-test-fix-backmerge-pr-validity-check-target"}],"documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request","status":"422"}
```

Also, the lane didn't fail, as it usually doesn't when the creation of PRs fails like this at the GitHub API level.

**Comment by iangmaia** [comment]
> I've tried to run a simple test:

Another very similar test, but with an empty commit: [it works fine](https://github.com/bloom/DayOne-Android/pull/4982).

**Comment by AliSoftware** [comment]
> ```
> iangmaia/test-fix-backmerge-pr-validity-check-target' of 'bloom/DayOne-Android
> ```

Strange, because checking the results of `merge-base` by running the git command in a Terminal, this returns the same sha1 for everyone, so I'd have expected the action to correctly detect that both branches pointed to the same commit and thus skip creating the PR… 🤔 

```
 19:36:08  📂 ~/Documents/Dev/apps/DayOne-Android/  (trunk) 
✓ $ git merge-base origin/merge/iangmaia-test-fix-backmerge-pr-validity-check-into-iangmaia-test-fix-backmerge-pr-validity-check-target origin/iangmaia/test-fix-backmerge-pr-validity-check-target
fc9356c15cba2d03b25112c6397b1c27949b4213

 19:36:20  📂 ~/Documents/Dev/apps/DayOne-Android/  (trunk) 
✓ $ git rev-parse origin/merge/iangmaia-test-fix-backmerge-pr-validity-check-into-iangmaia-test-fix-backmerge-pr-validity-check-target origin/iangmaia/test-fix-backmerge-pr-validity-check-target
fc9356c15cba2d03b25112c6397b1c27949b4213
fc9356c15cba2d03b25112c6397b1c27949b4213
```

So this means the reasoning we intended to apply is correct, but there's a bug in the current implementation I guess…

**Comment by AliSoftware** [comment]
@iangmaia I've pushed some commits that I think should fix the issue. Can you redo your tests after pointing to the latest commit of this branch? 🙇

**Review by iangmaia — APPROVED** [review]
I ran a few checks with the latest changes and I correctly had the Backmerge PR created or a `Nothing to merge from <source> into <target>. Skipping PR creation.` message.

:shipit:

**Pull request merged**
