### PR TITLE
Update Bundler config to fix/workaround #385

### PR DESCRIPTION
**Pull request by mokagio**
`BUNDLE_FORCE_RUBY_PLATFORM` `true` should force `nokogiri` being build via source. This seems wasteful given Bundler should be able to use the appropriate platform for it depending on the machine it's running from,
but that hasn't been the case for me recently, see https://github.com/wordpress-mobile/release-toolkit/issues/385.

Without this setting, I am unable to run `bundle exec rake new_release`, getting the `nokogiri` platform errors reported in #385.

Something is on my mind, though: Why does `rm -rf vendor/bundle && bundle install`work on my machine but the`bundle install` run from the `new_release` Rake task fails?

### CODE REVIEW

**Comment by mokagio** [comment]
Note: The build is currently [failing](https://buildkite.com/automattic/release-toolkit/builds/655#01821d7e-afe7-4179-b2f8-73251c0f79a8) because of an infrastructure issue.

image

**Comment by AliSoftware** [comment]
Maybe `BUNDLER_PLATFORM_SPECIFIC: "false"` was not enough and the seemingly-random choice from bundler between platform-agnostic vs platform-specific `nokogiri` is still unstable even with this? (See paaHJt-2Gx-p2 and https://github.com/wordpress-mobile/release-toolkit/pull/384#discussion_r935903177)

So even if you didn't seem to have the issue when you made the `5.1.0`, since I remember this (bundler choosing between ruby vs `x86_64-darwin`) was kinda flaky and random… maybe it's still worth adding that `BUNDLE_FORCE_RUBY_PLATFORM` too after all?

**Comment by AliSoftware** [comment]
Rebased this on top of the `release/5.2.0` branch (and updated the target branch of this PR accordingly) since I just encountered a similar issue while doing this new 5.2.0 release.

I will undraft and merge this once CI is green, and try updating `release/5.2.0` to get rid of the platform-specific nokogiri once it has landed in the release branch.

**Review by AliSoftware — APPROVED** [review]

**Comment by mokagio** [comment]
👍 

Sad that it had to come to this because it's yet another instance of Bundler being a bit unstable in the past couple of year, at least as far as my experience with it has been.

At the same time, I'm glad my PR was useful. Case in point for extracting knowledge out of one's brain whenever possible, specially in a distributed async-first organization 🤓

**Comment by AliSoftware** [comment]
> Case in point for extracting knowledge out of one's brain whenever possible, specially in a distributed async-first organization 🤓

💯 

tbh I'm still unsure if that definitively fixed the issue at its core or if I was lucky on the second run and all that was coincidental and that workaround didn't have a real effect on how `bundle` decides which version of `nokogiri` to pick… we'll see on subsequent releases, I guess.

**Pull request merged**
