### PR TITLE
Release 6.3.0 into trunk

### PR DESCRIPTION
**Pull request by spencertransier**
New version 6.3.0. Be sure to create a GitHub Release and tag once this PR gets merged.

### CODE REVIEW

**Comment by AliSoftware** [comment]
@spencertransier do you actively need a new version ASAP? Asking because I'm currently working on adding two small new actions on the toolkit that I'm hoping to PR by EOD and land by tomorrow, so maybe we could release everything at once instead of multiple releases? (even tho I'm fine to release two versions in close succession if you do need it)

**Comment by spencertransier** [comment]
@AliSoftware Adding Mac support for these actions is one of the last things needed before landing my DOApple Fastlane PR hopefully today, so it would be great to get these ASAP if possible.

**Review by AliSoftware — APPROVED** [review]
Ok, np, let's do it then 🙂

**Comment by spencertransier** [comment]
@AliSoftware Thank you, much appreciated! 😃

**Pull request merged**
