### PR TITLE
Require version_code parameter to be an Integer for Android hotfixes

### PR DESCRIPTION
**Pull request by mokagio**
When I created the hotfix branch for Simplenote Android 2.10.1, I erroneously replied "2.10.1" to the UI prompt for a version code value.

I didn't notice my mistake and pushed the branch, @theck13 had to fix it in his PR, see https://github.com/Automattic/simplenote-android/pull/1157/commits/cf3c979e27b5b1a9e661aa6201155e9546987d33.

### CODE REVIEW

**Comment by AliSoftware** [comment]
@mokagio Any reason this is still in Draft? 😅

**Comment by mokagio** [comment]
@AliSoftware oh yeah... thank you for pinging me about this. I had totally forgotten.

I was too hasty in opening the PR at the time and only realize it didn't work afterwards. _I should have updated the description or left a comment about it._

It doesn't work because of a Fastlane issue. [I opened a PR about it upstream](https://github.com/fastlane/fastlane/pull/18088).

**Comment by mokagio** [comment]
My PR has been merged. Just waiting for a new version of Fastlane to ship with it then I'll update the code here 👍

**Comment by AliSoftware** [comment]
fastlane 2.174.0 is out with your fix 🎉

**Comment by mokagio** [comment]
Ah! Thanks for merging `trunk` into this @spencertransier. It's been sitting here for _a long time_...

**Review by crazytonyli — APPROVED** [review]

**Review by spencertransier — APPROVED** [review]
No problem @mokagio! I saw it the other day and didn't see any reason not to move it forward 😄

**Pull request merged**
