### PR TITLE
Release 3.0.0 into trunk

### PR DESCRIPTION
**Pull request by mokagio**
New version 3.0.0. 

Be sure to create a GitHub Release and tag once this PR gets merged.

---

I'd like to release a new version so that we can [use the `buildkite_trigger_build` action in WordPress iOS](https://github.com/wordpress-mobile/WordPress-iOS/pull/17893) and ditch CircleCI for releases, ideally starting in 19.2 🤞 ⏱️ 

I haven't enabled auto-merge so I can merge, tag, push, and release once approved.

### CODE REVIEW

**Comment by AliSoftware** [comment]
There are a couple of small TODO/FIXME in the codebase right now that would be worth addressing before doing this new major version. (One that comes to mind is changing the default value for the default branch to `trunk` in the actions that use this)

Maybe not everything that is currently deprecated is ready to be already removed (the localize_projects stuff should probably wait for next major after that to get removed given we haven't transitioned to the new actions in client apps yet) but probably some quick-win ones could be addressed still?

**Comment by mokagio** [comment]
Thanks for the `TODO` suggestion and the quick review @AliSoftware.

I found four `TODO`s and no `FIXME` by grepping the code. As you've seen, I addressed two already. The others, are in `ios_download_strings_files_from_glotpress.rb` and depend on #296 which is still in draft.

Going to remove deprecated actions next, while I'm at it.

**Comment by AliSoftware** [comment]
Just a note that this PR is pending on https://github.com/wordpress-mobile/release-toolkit/pull/337 so a reminder not to approve/merge it until #337 lands first 🙂

**Review by AliSoftware — APPROVED** [review]
Just approved and merged #337 so we should now be good to go! 🎉

**Pull request merged**
